const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const { spawnSync } = require('node:child_process')
const script = path.resolve(__dirname, '../scripts/ai-handoff.js')
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'handoff-test-'))
const specFile = path.join(temp, 'spec.json'), output = path.join(temp, 'handoff'), assets = path.join(temp, 'assets')
const spec = { schemaVersion: 1, title: 'Test', coreLoop: 'Choose and score', style: 'flat', acceptance: ['score updates'], assets: [{ id: 'icon', kind: 'image', path: 'images/icon.png', width: 1, height: 1, maxBytes: 200, prompt: 'icon' }] }
const run = (...args) => spawnSync(process.execPath, [script, ...args], { encoding: 'utf8' })
const write = value => fs.writeFileSync(specFile, JSON.stringify(value))
try {
  write(spec)
  assert.equal(run('init', specFile, output).status, 0)
  const manifestFile = path.join(output, 'manifest.json')
  const original = fs.readFileSync(manifestFile, 'utf8')
  assert.equal(run('init', specFile, output).status, 1)
  assert.equal(fs.readFileSync(manifestFile, 'utf8'), original)
  fs.mkdirSync(path.join(assets, 'images'), { recursive: true })
  assert.equal(run('check', manifestFile, assets).status, 1)
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9X0AAAAASUVORK5CYII=', 'base64')
  const file = path.join(assets, 'images/icon.png')
  fs.writeFileSync(file, png)
  assert.equal(run('check', manifestFile, assets).status, 1, 'Review and provenance required')
  const manifest = JSON.parse(original)
  Object.assign(manifest.assets[0], { source: 'test fixture', sourceReference: 'fixture-1', usageTerms: 'test only', reviewed: true })
  fs.writeFileSync(manifestFile, JSON.stringify(manifest))
  const result = run('check', manifestFile, assets)
  assert.equal(result.status, 0, result.stderr)
  assert.equal(JSON.parse(result.stdout).results[0].sha256.length, 64)
  const project = path.join(temp, 'game')
  fs.mkdirSync(project)
  fs.writeFileSync(path.join(project, 'project.config.json'), JSON.stringify({ compileType: 'game' }))
  const importing = (...extra) => run('import', manifestFile, assets, project, 'v1', ...extra)
  assert.equal(importing().status, 1, 'Unbound review cannot import')
  manifest.assets[0].reviewedSha256 = JSON.parse(result.stdout).results[0].sha256
  fs.writeFileSync(manifestFile, JSON.stringify(manifest))
  assert.equal(importing().status, 0, 'Dry run passes')
  assert.equal(fs.existsSync(path.join(project, 'ai-assets')), false, 'Dry run must not write')
  assert.equal(importing('--apply').status, 0)
  const bundle = path.join(project, 'ai-assets/v1')
  assert.deepEqual(fs.readFileSync(path.join(bundle, 'images/icon.png')), png)
  assert.equal(require(path.join(bundle, 'index.js')).icon.path, 'ai-assets/v1/images/icon.png')
  const receipt = JSON.parse(fs.readFileSync(path.join(bundle, 'receipt.json')))
  assert.equal(receipt.assets[0].sha256, manifest.assets[0].reviewedSha256)
  assert.equal(importing('--apply').status, 1, 'Existing version must not be overwritten')
  const differentBytes = Buffer.from(png); differentBytes[differentBytes.length - 1] ^= 1
  fs.writeFileSync(file, differentBytes)
  assert.equal(run('import', manifestFile, assets, project, 'v2', '--apply').status, 1, 'Same dimensions but changed bytes invalidates review')
  assert.equal(fs.existsSync(path.join(project, 'ai-assets/v2')), false)
  fs.writeFileSync(file, png)
  const linkedProject = path.join(temp, 'linked-game')
  fs.mkdirSync(linkedProject)
  fs.writeFileSync(path.join(linkedProject, 'project.config.json'), JSON.stringify({ compileType: 'game' }))
  fs.symlinkSync(assets, path.join(linkedProject, 'ai-assets'))
  assert.equal(run('import', manifestFile, assets, linkedProject, 'v1', '--apply').status, 1)
  const changed = Buffer.from(png); changed.writeUInt32BE(2, 16)
  fs.writeFileSync(file, changed)
  assert.equal(run('check', manifestFile, assets).status, 1, 'Wrong dimensions fail')
  fs.writeFileSync(file, Buffer.alloc(201))
  assert.equal(run('check', manifestFile, assets).status, 1, 'Oversized/invalid PNG fails')
  fs.unlinkSync(file)
  fs.writeFileSync(path.join(temp, 'outside.png'), png)
  fs.symlinkSync(path.join(temp, 'outside.png'), file)
  const escaped = run('check', manifestFile, assets)
  assert.equal(escaped.status, 1)
  assert.match(escaped.stdout, /Symlink escapes/)
  write({ ...spec, assets: [{ ...spec.assets[0], path: '../outside.png' }] })
  const invalidOutput = path.join(temp, 'invalid')
  assert.equal(run('init', specFile, invalidOutput).status, 1)
  assert.equal(fs.existsSync(invalidOutput), false)
  write({ ...spec, assets: [spec.assets[0], spec.assets[0]] })
  assert.equal(run('init', specFile, invalidOutput).status, 1)
  console.log('Passed: generation, overwrite protection, missing assets, review/provenance, PNG dimensions, byte budget, fingerprint, path confinement, import preview, resource index, version protection and changed-review rejection.')
} finally { fs.rmSync(temp, { recursive: true, force: true }) }
